# Generated by Django 3.0.8 on 2020-08-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_id',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
